apiVersion: v1
kind: Service
metadata:
  name: reniec-service
  namespace: lizreniec 
spec:
  selector:
    app: reniec
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
